- CAmkES/index.md
- CAmkESNext.md
- FrequentlyAskedQuestions.md
- Getting_started.md
- ReleaseProcess.md
- Status.md
- index.md
> Fix GitHub-related capitalization

- CAmkES/index.md
Update the instructions to the new build system
> Update Camkes project instructions

- _sel4_release/index.md
@yyshen is the statement about ARM VMs true?
> manual release timeline update

- HostDependencies.md
Without this option, `ccmake ..` does not work.
> Add cmake-curses-gui to dependencies

- FrequentlyAskedQuestions.md
> Update ssrg to TS in URLs

- FrequentlyAskedQuestions.md
also fixed "proven" to "proved"
> Added code-size questions

- _includes/footer.html
- _includes/tutorial.md
This also provides a fix for #55
> Fix broken edit URLs

- processes/code-review.md
- processes/roles.md
* more details on pull request reviewing and tests
* small updates to Committer role description
* small markdown tweaks
* document that Benno has reviewer role
> Pull requests

- processes/index.md
> Change Mattermost URL

- _data/maintained.yml
The main effect of this should be that the ssrg-bot monitors them
for pull requests.
> Add more maintained repos

- Hardware/rockpro64.md
Signed-off-by: Samuel Tyler <samuel.tyler005@gmail.com>
This assumes use of UEFI, which is pending over at https://github.com/seL4/seL4_tools/pull/61
> Add RockPro64 documentation

- _config.yml
- content_collections/_releases/camkes/camkes-3.10.0.md
- content_collections/_releases/capdl/0.2.1.md
- content_collections/_releases/sel4/12.1.0.md
This PR takes the CHANGES files from the relevant repositories that have new releases and throws them into the docsite. Also update the configuration to point to the new releases.
> New release

- _includes/custom-navbar.html
Now that a new release has been announced on the seL4 discourse forum,
this commit updates the link to point to that new announcement.
Signed-off-by: Damon Lee <Damon.Lee@data61.csiro.au>
> Update release announcement link

- Hardware/Rpi3.md
Basically https://github.com/seL4/docs/pull/83 from @fabriziobertocci squashed
> Add instructions to TFTP boot on RPI 3B+

- processes/code-review.md
This is for actual new features only, not necessarily for small tweaks.
Examples would be something like a new fast path, MCS, or anything that required an RFC.
> clarify that new features need new tests

- GettingStarted.md
as @Xaphiosis noticed, the code blocks didn't render correctly
> fix code blocks

- processes/emails.md
> remove CLA contact

- CommunityProjects.md
- GettingStarted.md
- Hardware/CEI_TK1_SOM/L4TCan/index.md
- _data/projects/camkes.yml
- _data/projects/l4v.yml
- processes/docs-contributing.md
- processes/index.md
- processes/rfc-process.md
- processes/websites.md
- projects/l4v/index.md
- projects/roadmap.md
- projects/sel4/documentation.md
- projects/sel4/frequently-asked-questions.md
The TS website has moved to its own domain.
> update D61 links to trustworthy.systems

- processes/rfc-process.md
Documents the additional (optional) stage-1 approval step and fixes some typos.
> rfc-process: document stage 1 approval

- tools/Dockerfile
Small updates to keep the website docker builder working.
> Docker fixes

- Hardware/sabreLite.md
Thanks to @robs-cse for pointing out the new link.
> fix sabre-lite link

- .github/workflows/build.yml
Previously, file would only be added or modified, but not removed.
> github: remove files on sync

- Hardware/JetsonTX2.md
The TX2 now also supports SMP.
(Forgot to add to the PR in #130 :-))
> Further TX2 details update

- processes/docs-contributing.md
Follow-up from https://github.com/seL4/docs/pull/136#discussion_r832755706
> point to devel mailing list

- projects/sel4/frequently-asked-questions.md
(also removes outdated comment on contributor license agreement)
> update FAQ with RISCV+AArch64 proofs

- Hardware/CEI_TK1_SOM/index.md
- Hardware/hifive.md
- Hardware/imx8mm.md
- projects/sel4/verified-configurations.md
- add more info an which features are verified for which board
- bring info up-to-date (mainly adding security proofs for RISCV)
-
> update verification status

- Hardware/CEI_TK1_SOM/index.md
- Hardware/JetsonTX2.md
- Hardware/hifive.md
- Hardware/index.md
- Hardware/sabreLite.md
- projects/sel4/verified-configurations.md
- complete the description of the full list of current verified configs
- add back-links from the hardware table to verified configs
- clean up tags in the hardware list
> more verification status update

- _data/projects/l4v.yml
- add AARCH64 project
- update MCS verification to Proofcraft
> roadmap update

- Hardware/polarfire.md
The polarfire platform is supported but does not have a page on the website. This commit adds a polarfire page.
> hardware: add page for polarfire

- processes/test-status.md
Not strictly speaking regenerated from source, but it's what the script would have produced.
> test-status: add web server CI

- processes/roles.md
- remove people who have left
- reflect two new Committers from UNSW
- update affiliations
> roles: update affiliation + committers membership

- processes/roles.md
Syncing committers list, adding Indan to reviewers.
> roles: update reviewer+committer lists

- projects/dockerfiles/index.md
Advice to try giving Docker container more memory if QEMU fails.
Signed-off-by: Robert Sison <robert.sison@unimelb.edu.au>
> Update dockerfiles index.md

- Tutorials/index.md
"these" is repeated, remove one
Signed-off-by: Duan Wenrui <63503646+dwr2001@users.noreply.github.com>
> "these" is repeated, remove one

- Hardware/index.md
I believe that ARMv6 is no long supported and on RISC-V SMP and FPU support is already added right?
> Minor updates to platform support page

- processes/test-status.md
Workflow deleted in seL4/website#276
> remove obsolete Bamboo workflow reference

- processes/roles.md
The TSC has invited Alwin to the reviewer role.
> add Alwin as reviewer

- projects/sel4/frequently-asked-questions.md
Make terminology clearer and state that RISC-V SMP is supported.
> Update FAQ multi-core answer

- _data/projects/l4v.yml
- add projected AArch64 completion date
- add multikernel project
> update project roadmap

- _data/projects/sel4.yml
End of this year was too optimistic.
> Update roadmap with clarification

- processes/test-status.md
- adds microkit and rust repos
- removes new PR workflows
- updates broken badge URL format
Generated from changes in seL4/ci-actions#338
> test-status: regenerate for new repos+workflows

- Hardware/JetsonTX2.md
- _data/projects/l4v.yml
- projects/sel4/verified-configurations.md
- AArch64 functional correctness is complete
- AArch64 integrity proofs are starting
- multikernel concurrency framework is complete
> roadmap: update AARCH64 and Multikernel status

- Hardware/VMware/seL4vmw.py
- style checker udpate is complaining about commented out line; remove.
- remove unused import
- fix other trivial python lints
> trivial: python style + lint fixes

- Hardware/cheshire.md
Documentation for https://github.com/seL4/seL4/pull/1354
> Added documentation for Cheshire (CVA6)

- _includes/header.html
> header: fix Projects link

- _config.yml
- _data/projects/microkit.yml
- content_collections/_releases/microkit/2.0.0.md
Changes should be done but I haven't made the GitHub release so hold off on merging until I do that.
> Add Microkit 2.0.0 release

- _config.yml
- _data/projects/microkit.yml
- content_collections/_releases/microkit/2.0.1.md
Not ready for merging but @lsf37 if you can review then I'll merge once the release is actually out.
> Add Microkit 2.0.1 release

- processes/roles.md
> Redirect roles.md to sel4.systems

- _includes/seL4-deps.md
Occasionally needed by elf-loader-tool.
Closes #227
> Add xxd to dependencies
