seL4/docs

Hardware/BeagleBoard.md
Update name of the generated image, clarified (and updated) the instructions to copy the image and the command to boot from sd card.
Added a note about the load address to use and how to change it.
Added a note to cover situations where the bootelf command is not available
=> Added more information about load address and boot command

FrequentlyAskedQuestions.md
Fixed a line-wrap/line-break typo in the heading: "How do I tell which code in GitHub is covered by the proof and which
isn’t?". Typo was probably due to the heading being too long for the line-wrap settings in whatever editor/text-processor that was used.
=> Fixed a minor typo in a heading.

HostDependencies.md
Jessie is too old now; even stretch needs cmake from stretch-backports.
=> Changes for Debian Stretch

HostDependencies.md
ubuntu 18.04 has device-tree-compiler package not dtc
=> dtc package fix

Tutorials/index.md
I believe aenum and pyelftools modules are also needed to build tutorials, I realized this when trying to build hello-world.
=> aenum and pyelftools python modules are required

Hardware/RISCV.md
`kernel/gcc.cmake` doesn't have a default case for when `RISCV32` isn't set, so the build ends up using vanilla `gcc`.
=> Clarify 32-bit build instructions.

FrequentlyAskedQuestions.md
The minor error was that messages are delivered to a receiver, not a sender
=> Fix grammar and minor error in FAQ

FrequentlyAskedQuestions.md
Add 1 to the depth of each heading for the FrequentlyAskedQuestions
page except the page title heading.
The table of contents generation assumes all headings on the page start
from depth 2 and the page title is the only heading with depth 1.
=> FAQ: Fix heading depth for correct TOC

VM/CAmkESARMVM.md
* The name of the application has changed
* The build for TK1 now produces an EFI image, not an ELF file
I'm not sure about the booting part really, as I don't have TK1 to test. I'm just assuming that since it's a EFI app u-boot should be able to load it as such.
=> Update ARM VMM documentation

README.md
The README was still pointing to the old location.
=> Update docs-contributing.md link

projects/buildsystem/using.md
The cmake command needs to be given a path to the build directory, not to the source directory.
=> Give correct path for cmake configuration

projects/sel4test/index.md
It is not necessarily obvious that CTRL+A and X are two separate
keypresses. I hadn't used qemu in a while and had to look it up even
after reading the instructions. This should make it a bit more clear.
=> Trivial: Clarify keyboard shortcut for exiting qemu.

projects/l4v/index.md
blog and README link were swapped
=> trivial: fix swapped links

processes/roles.md
Luke has left D61 for greener pastures and stepped down from the foundation admin role, at least for now.
=> admin role: Luke has stepped down

.github/workflows/build.yml
This GitHub action replaces the corresponding bamboo job (which can then be turned off).
The site is built (for testing) on every pull request, but only deployed on push/merge to the `master` branch, and in addition by schedule (once a night). The latter is to catch changes in the repositories that the doc site pulls in, which are not always accompanied by a pull request here.
=> GitHub action to build and deploy the doc site

.github/workflows/build.yml
The website build has failed the past few days, I assume because the underlying Ubuntu install changed on the build agents. This PR fixes the build.
=> install bundler for website build

processes/release-process.md
As a result of things changing since the last release, I figured it would be a good idea to update the release procedure. Given that we're moving more towards on GitHub and being more open, it makes sense that this should be on a publicly accessible location.
=> Add release procedure documentation

.github/workflows/build.yml
The workflow dispatch event lets you manually kick off a website build
and deploy cycle. Useful for when one of the dependencies has changed
and you don't want to wait for the schedule to pick it up.
=> github: allow manual build kick-off

processes/roles.md
Axel and Yanyan are now committers, and the list of committers is now spelled out explicitly instead of referring to the github org.
=> roles: reflect role changes; spell out committers

processes/roles.md
Yanyan is now at NIO. Zoltan's affiliation is strictly speaking not right either (not quite at UNSW yet), but it should be official soon.
=> roles: update Yanyan's affiliation

_includes/footer.html
The {% capture %} expression previously generated a file path and therefore URL that had newline characters in it. Most web browsers just ignore these, but it's not strictly valid HTML and some link checkers choke on it.
=> footer: make sure edit URL contains no newlines

.bundle/config, .gitignore
Make sure that the Makefile does not try to install global gems, because this only works with super user privileges.
This also fixes seL4/sel4webserver-manifest#2
=> bundler: force local install of ruby gems

processes/release-process.md
- remove Bamboo references, releases are now directly on GitHub
- don't forget verification releases
- text tweaks for clarity/typos
=> release: clarify release process

_config.yml, content_collections/_dependencies/camkes.md, content_collections/_releases/camkes/camkes-3.2.0.md, projects/buildsystem/incorporating.md, projects/camkes-vm/index.md, projects/camkes/seL4SharedDataWithCaps.md, projects/dockerfiles/index.md, projects/user_libs/index.md
* config: remove duplicate key ("url:" was set twice. This removes the empty version.)
* Update URLs and examples for everything that was moved from seL4proj to the seL4 org.
=> sel4proj update

CommunityProjects.md
:wave: 
This commit adds [ferros](https://github.com/auxoncorp/ferros) to the community projects page.
Also fwiw, the Robigalia link appears to be dead.
=> Add ferros to community projects page

CommunityProjects.md
The main site seems to have disappeared, link to the gitlab collection instead.
=> fix Robigalia link

content_collections/_dependencies/sel4.md
The seL4 manual requires a few extra latex packages, in particular texlive-latex-extra and texlive-fonts-extra.
=> host-deps: add LaTeX dependencies for manual

_data/maintained.yml
- camkes-arm-vm (and -manifest) is deprecated and archived,
- mcs-examples (and -manifest) have never been in maintained status
- sel4-tutorials somehow made it into the manifest list
Closes #112
=> update maintained repo list

processes/git-conventions.md
Make explicit the convention that code should only be restyled when it
already being edited for other reasons. This is to limit change amplification
from small incremental style changes that aren't coupled to new-features
or bug-fixes.
This is a convention that has been selectively enforced historically[1], but hasn't been written down anywhere.  This PR can also serve to discuss whether the convention should continue to be enforced or not.
[1] https://github.com/seL4/util_libs/pull/84#issuecomment-841163630
=> git-conventions: Avoid style-only PRs

Hardware/index.md
We're already filtering by architecture (arm vs risc-V); having the table sorted by platform name makes it easier to find the 
platform you're interested in.
Signed-off-by: Peter Chubb <peter.chubb@unsw.edu.au>
=> Sort hardware by platform, not architecture.

assets/css/style.scss
Signed-off-by: matt rice <ratmice@gmail.com>
If you look at https://docs.sel4.systems/GettingStarted 
the code blocks there are being wrapped all onto one line,
this changes the css so each line of the code block will be on its own.
=> make code blocks use preformatted whitespace.

projects/sel4/manual-api-generation.md
This is of course predicated on pr seL4/seL4#789, I had missed this link to the dtd, on my previous pass looking through the all the repos.
Signed-off-by: matt rice <ratmice@gmail.com>
=> update link from dtd to xsd in manual gen page

.github/workflows/build.yml
Fixes: https://github.com/seL4/docs/issues/135
Forks do not have a valid `secrets.GH_TOKEN`, thus the action will always fail.
=> github: do not deploy on forks

Hardware/MaaXBoard.md
This pull request is a call for feedback and comment on an initial implementation for supporting seL4 on the Avnet MaaXBoard, with the intention of the changes being merged back to the main docs repository. This pull request is dependent on three other pull requests which provide the core support for the MaaXBoard: https://github.com/seL4/seL4/pull/829, https://github.com/seL4/seL4_tools/pull/144, https://github.com/seL4/util_libs/pull/129.
This pull request adds a new row to the Supported Platforms table and provides the basic seL4test instructions.
=> Add support for the Avnet MaaXBoard (docs)

Hardware/ariane.md, Hardware/hifive.md, Hardware/rocketchip.md, Hardware/spike.md, _includes/risc-v.md, content_collections/_dependencies/camkes.md, content_collections/_dependencies/sel4.md
This PR does minor clean up and adds instructions for Ubuntu 20.04 and 22.04 on the "Host Dependencies" page.
This is a draft as:
=> Add host dependencies instructions for Ubuntu 20.04 and 22.04

tools/Dockerfile
Building the site for the seL4 tutorials now needs the full `camkes-deps` in python, which in turns needs `python3-dev`.
Native and GitHub builds are unaffected, this just updates the available background dependencies in the docker container provided for building the site.
=> docker: update docker env for seL4-tutorials

CommunityProjects.md
- updating the page a bit.
- Adding NeptuneOS (WinNT), seL4 Core Platform, Laot, linkt to TS projects
- https://rbg.systems seems dead, use https://gitlab.com/robigalia
I wonder if we should remove Python there if we can give at least one link to a project
=> update community projects

projects/sel4/frequently-asked-questions.md
The hardware platform list is useful if you have a platform and want to know if it is supported, the verified config list is useful if you just want a list of what is verified.
=> faq: link to verified configs

Hardware/ultra96v2.md
Added a page for the ultra96v2 since its a supported seL4 platform, and doesn't have a page on the website.
=> hardware: add page for ultra96v2

Hardware/ZCU102.md
seL4_tools was recently updated to differentiate the zynqmp platforms. This commit updates the ZCU102 guidelines to explicitly compile for the ZCU102 instead of the generic zynqmp.
Signed-off-by: Chris Guikema <chris.guikema@dornerworks.com>
=> zcu102: update cmake_plat from zynqmp to zcu102

.github/workflows/build.yml
- pin runner OS version to Ubuntu 20.04, which contains the right versions of ruby + bundler until we have updated the main build
- bump action versions to Node 16 actions
=> fix GitHub docsite build

processes/roles.md
TSC members have Committer and/or Admin access, depending on how involved they are with the administration of the repositories.
=> roles: clarify GitHub access of TSC members

GettingStarted.md, _data/sidebar.yml, processes/licenses.md, projects/sel4/frequently-asked-questions.md
Licensing was previously described on
<https://sel4.systems/Info/license.pml>, but only linked-to from the docs site. Additionally, the description there was a bit sparse and old.
Thanks to @StefanSchroeder for alerting us to the broken link in #171
=> Update license description and move into this repo

Hardware/OdroidC4.md
This PR simply adds a dedicated page for the Odroid-C4, the board has actually been supported since https://github.com/seL4/seL4/pull/447.
The main difference between this page and the Odroid-C2 page is that we did not encounter any kernel corruption issues when using the default U-Boot that came on the board and seL4test.
=> Add Odroid-C4 as supported platform

processes/test-status.md
The prepare-binary-verification job is now integrated into the main l4v workflows, so doesn't show up separately any more.
=> test-status: remove binary verification

_data/projects/camkes.yml
The Cogent project is no longer actively developed on top of seL4.
=> drop support for Cogent

Hardware/Rpi4.md
Depends on https://github.com/seL4/seL4_tools/pull/167
I have another patch that revamps the RPi documentation but it's not done yet hopefully I'll get back to it soon but this patch at least means that the booting command is correct.
=> hardware: update booting command for RPi4

content_collections/_dependencies/camkes.md, content_collections/_dependencies/sel4.md
We do not need python2 in order to build seL4 anymore, and I believe the same applies for CAmkES.
=> Remove python2 from host dependencies

content_collections/_dependencies/camkes.md, content_collections/_dependencies/sel4.md
The Ubuntu 18.04 OS has been deprecated since April 2023.
=> Remove dependency instructions for Ubuntu 18.04

.github/workflows/build.yml
The site figures out page modification dates by git commit, but if we only fetch the latest revision, all dates will just have the last commit.
Fixes #196
=> github: fetch history for page modification dates

Hardware/CEI_TK1_SOM/index.md, Hardware/OdroidXU4.md, Hardware/imx8mm.md, Hardware/sabreLite.md, projects/sel4/verified-configurations.md
This adds `exynos5` as verified configuration and marks the verification of `imx8mm` as maintained.
- updates the hardware status page
- updates the verified configs page
- points to cmake configs in the seL4 repo
=> update status of verified configs

CommunityProjects.md, _data/projects/microkit.yml, index.md, projects/index.html, projects/microkit/index.md
Integrates the seL4 Microkit project into the official seL4 documentation.
=> Add the seL4 Microkit project

processes/rfc-process.md
The old RFC dashboard had a broken issue filter and was not editable any more. Replace with a new, working dashboard.
=> rfc: fix RFC dashboard link

.github/workflows/build.yml
Fixes github website build.
The latest version of bundler requires ruby 3.0, but we're still on 2.7 for now.
=> github: fix bundler version

Hardware/index.md
On the `Hardware supported` page, the table for RISC-V didn't have a proper header line (greyed and bold). It is now consistent with the ARM and X86 tables.
=> Docsite hardware page: make table headers consistent

Hardware/index.md
- added a high-level summary
- added a description of the table
- added a link to the verified configuration page
- small language tweaks
=> hardware: improve the text

Hardware/index.md, projects/sel4/verified-configurations.md
- on the suported hardware page, moved x86 table after ARM and RISC-V (to reflect main focus)
- on verified configuration page: also moved x86 last and also reordered the list to match the text
=> hardware and verified config: swap order

Hardware/index.md, _data/sidebar.yml, index.md
Used the term "Supported hardware platforms" (after discussion with Gerwin) for: the Hardware page title, the side menu and the landing page (table of content).
=> hardware: make title consistent in page/menus

.github/workflows/build.yml
GitHub has started issuing warnings for node16 actions.
=> github: bump actions to node20

Hardware/index.md, projects/sel4/kernel-contribution.md, projects/sel4/platf-owner.md
* supported platform:
* added a "Not in the lists below?" section
* kernel-contribution.html:
* added an intro paragraph linking back to the supported platforms page and other options than developing yourself
* Added link to new platform owner page
* BSD -> BSD/platform (the porting page uses 'platform')
* fixed small typo (Contrbution)
* new platform owner page
=> hardware: info for not supported platforms

projects/sel4/porting.md
Work-in-progress changes - will try finish within the next couple days,
=> Improving documentation for porting seL4 and making it up-to-date

content_collections/_dependencies/sel4.md
- Debian Stretch hasn't been supported for a while. Remove the instructions for it.
- Fix broken links to docker files -- firstly, the content was never in those files (but the scripts instead), and secondly the links were broken. They now point to the script files that contain the actual dependencies.
=> seL4 deps: fix broken links; retire Debian Stretch

processes/style-guide.md
3.1 is the version available in Ubuntu 20.04LTS, which is recommended in the current install instructions. Later versions also work and output seems to be stable for our sources. Versions earlier than 3.0 no longer work correctly with the options in our .astylerc.
=> style: update astyle version

_config.yml
https://github.com/matrixfox/jekyll-theme-bootstrap/commits/master/ has new commits which break the build. Fix version to v0.0.5, which is what we've been running all this time.
=> config: fix bootstrap theme version

Hardware/index.md, _plugins/include_absolute.rb
- address Ruby "Using the last argument as keyword parameters is deprecated" warning
- fix the Liquid syntax error that was drowned out by those warnings
=> remove warnings

_config.yml, _includes/custom-navbar.html, content_collections/_releases/camkes/camkes-3.11.0.md, content_collections/_releases/capdl/0.3.0.md, content_collections/_releases/microkit/1.3.0.md, content_collections/_releases/sel4/13.0.0.md
To be merged when CI release process is completed and releases are fully tagged.
This adds release notes for seL4, Microkit, CAmkES, and capDL and updates the nav bar versions for all of these.
=> add new releases

Hardware/index.md, _includes/project-sidebar.html
- latest release on top
- remove mcs from side bar (confusing, and still available from other navigation)
- remove experimental seL4 branches from side bar, because there aren't any
=> clean up release sidebar

_data/projects/microkit.yml, _includes/project-sidebar.html
Looks like this:
Didn't know if there was a better way of dealing with a custom field in the project YAML file.
Draft since these URLs don't exist yet.
=> Add downloads section for Microkit SDK

tools/Dockerfile
All required python dependencies should be part of camkes-deps (which includes sel4-deps). If they are not, these packages should be updated.
=> docker: clean up python dependencies

content_collections/_releases/microkit/1.4.1.md
Given that people will probably refer to these in the future, it's worth fixing the typos.
=> Fix typos in Microkit 1.4.1 release notes

GettingStarted.md, projects/sel4/frequently-asked-questions.md, projects/sel4/kernel-contribution.md, projects/sel4/verified-configurations.md
Some links to the seL4 Foundation website were broken when the website moved to GitHub pages.
=> Update some links to foundation website

Hardware/HiKey/index.md, Hardware/JetsonTX2.md, Hardware/OdroidC2.md, Hardware/OdroidC4.md, Hardware/OdroidXU.md, Hardware/Rpi4.md, Hardware/ZC706.md, Hardware/ZCU102.md, Hardware/imx8mm.md, Hardware/jetsontk1.md, Hardware/odroidx.md, Makefile, projects/sel4/verified-configurations.md
Adding the verified platforms that are merged (not yet the ones in https://github.com/seL4/seL4/pull/1373).
The way these are presented makes less sense the more platforms we add, but for now this should still be Ok. We'll be working on reorganising that in the docsite refresh.
=> add more verified platforms

Tutorials/get-the-tutorials.md, _includes/pip-instructions.md, content_collections/_dependencies/camkes.md, content_collections/_dependencies/sel4.md
Homebrew and newer versions of Debian and Ubuntu do not allow you to simply `pip install` anymore. Since these Python dependencies are available via `apt` or `brew` we have to setup a virtual environment.
I chose to leave the `pip install` instructions since there are still distros and current versions of Ubuntu that are fine with it. Also the default macOS Python via xcode command line utils is fine with `pip install`. Not sure if it'll just lead to more confusion though.
I'm having issues with building the docs site so whoever reviews should also check that the rendered pages seems sane.
=> Adapt setup instructions for externally managed Python versions

.github/workflows/build.yml, .linkcheck-ignore.yml
20.04 is no longer supported. Python and ruby version remain pinned.
=> github: bump runner OS version

Tutorials/index.md
The redirect (removed in df31e5ccb8) is necessary, because the generated project side bar links to it.
=> tutorials: re-add redirect

Hardware/X64.md, Hardware/index.md, _includes/hw-info.html, _includes/pc99.md
- split up the IA32 page into one for ia32 and one for x64 (same included text, but different hardware info settings)
- adjust hw-info accordingly for IOMMU vs SMMU
- set expectations for simulation target platforms in the simulation section
I think this should close #243 -- we now do have info for each platform page (including pc99), and including it in the hardware table would give the wrong impression that these platforms provide a full simulation environment. The new explanation bit in the simulation section hopefully explains that part.
=> Provide hw-info for PC99 and explain simulation targets

assets/js/menu.js
Code highlight blocks have the form
```
<div class="higlight"><pre><code>...
```
(wrapped in another div that specifies the language). The copy-button insertion relies on the presence of the `<div>`. The previous CSS selector was too loose for that, it allowed the `<pre>` to be a direct descendant of any `<div>` at any position, so it could be
```
<div> <p>..</p> etc <pre><code>
```
which does happen when the syntax highlighter does not recognise the language that is passed in from the code block (```lang). This leads to mis-styling of the copy buttons, in particular, the position will be relative to the wrapping div, which might be anywhere (usually the page container), and consequently the hover group for showing the copy buttons may also be the page container.
Making the selector …
```
=> copy button: narrower CSS selector

Hardware/ZC706.md
According to #237 it is likely that current U-Boot works without patch. In any case the current instructions do not work, because the given patch does not apply any more.
=> zc706: remove outdated instructions
